# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy PHP App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup PHP with extensions'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          # ✅ USAR LA MISMA VERSIÓN QUE AZURE
          extensions: mongodb-2.0.0, gd, imagick, redis
          
      - name: 'Install Composer dependencies'
        run: |
          # ✅ USAR LA VERSIÓN 2.0.0 QUE SÍ EXISTE
          composer require mongodb/mongodb:2.0.0 --ignore-platform-req=ext-mongodb
          composer install --no-interaction --no-dev --optimize-autoloader --ignore-platform-req=ext-mongodb

      # ✅ CREAR PAQUETE ZIP SELLADO
      - name: 'Create zip package for deployment'
        run: zip -r deployment.zip . -x ".git/*" -x ".github/*"

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'IPD-GameOn'
          slot-name: 'Production'
          package: deployment.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CA1C706A601649A6B4B0C8E61A25B604 }}