# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy PHP App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup PHP with extensions'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mongodb-1.17.0, gd, imagick, redis
          
      - name: 'Install Composer dependencies'
        run: composer install --no-interaction --no-dev --optimize-autoloader

      # ✅ PASO CLAVE: Eliminar los archivos de Composer antes de desplegar.
      # Esto evita que el sistema de construcción de Azure (Oryx) se active.
      - name: 'Remove Composer files before deployment'
        run: rm composer.json composer.lock

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'IPD-GameOn'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CA1C706A601649A6B4B0C8E61A25B604 }}