# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - IPD-GameOn

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mongodb

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: 'composer.json'

      # 🎯 SOLUCIÓN AZURE: Forzar la versión de MongoDB compatible con el servidor
      - name: Install compatible MongoDB library for Azure
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          composer require "mongodb/mongodb:^1.16.0" --no-interaction --no-update
          composer update "mongodb/mongodb" --with-all-dependencies --no-interaction --prefer-dist --no-dev --optimize-autoloader

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'IPD-GameOn'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CA1C706A601649A6B4B0C8E61A25B604 }}